Controllers/WebboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using WebboardMVC.Models;
using WebboardMVC.ViewModels;

namespace WebboardMVC.Controllers
{
    [Authorize(Roles ="Admin,Staff,Member")]
    public class WebboardController : Controller
    {
        private readonly AppDbContext _db;

        public WebboardController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var ks =  _db.Kratoos.Where(a => a.CategoryId != null).ToList();
            if (ks == null)
            {
                return NotFound();
            }
            return View(ks);
        }

        public IActionResult Create()
        {
            ViewData["CategoriesLists"] = new SelectList(_db.Categories,"CategoryId","CategoryName");
            return View();  
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Kratoo data) 
        {
           
                data.RecordDate = DateTime.Now.ToString();
                data.ViewCount = 1;
                data.ReplyCount = 0;
                data.UserIp = HttpContext.Connection.RemoteIpAddress.ToString();
                data.IsShow = "true";
                data.Username = User.Identity.Name;

                _db.Kratoos.Add(data);
               await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            
            //ViewData["CategoriesLists"] = new SelectList(_db.Categories, "CategoryId", "CategoryName",data.CategoryId);
            //return View(data);
        }

        public async Task<IActionResult> kratoosByCategoryId(int id) 
        {
            var ks = _db.Kratoos
                    .Where(k => k.IsShow == "true" && k.CategoryId == id)
                    .OrderByDescending(k => k.RecordDate)
                    .ToList();
            if (ks == null)
            {
                return NotFound();
            }
            return View("Index", ks);
        }

        public async Task<IActionResult> Search(string q) 
        {
            var ks = _db.Kratoos
                .OrderByDescending(k => k.RecordDate)
                .Where(u => u.IsShow == "true")
                .Where(i=>i.KratooTopic.Contains(q));
            if (ks == null)
            {
                return NotFound();
            }
            return View("Index",await ks.ToListAsync());
        }

        public async Task<IActionResult> kratooComments(int id)
        {
            var kc =await _db.Kratoos
                .Where(i => i.IsShow == "true")
                .FirstOrDefaultAsync(k=>k.Kid==id);

            if (kc == null) 
            {
                return NotFound();
            }
            if(id != kc.Kid) 
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var viewcount = kc.ViewCount;
                    viewcount++;
                    kc.ViewCount = viewcount;
                    _db.Update(kc);
                    await _db.SaveChangesAsync();
                }
                catch (DBConcurrencyException)
                {
                    var result = _db.Kratoos.Any(k => k.Kid ==id);
                    if (result==false)
                    {
                        return NotFound();
                    }
                }
            }
            IQueryable<Comment>cs = _db.Comments
                .OrderBy(c=>c.CommentNo)
                .Where(i=>i.IsShow == "true")
                .Where(j=>j.Kid==id);

            var viewmodel = new KratooCommentViewModel()
            {
                Kratoo = kc,
                CommentList= cs
            };
            ViewData["KratooCommentViewModel"] = viewmodel;
            return View("KratooComments");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> kratooComments(Comment data) 
        {
           var cs = await _db.Comments
                .OrderByDescending(i=> i.CommentNo)
                .Where(c=>c.Kid==data.Kid)
                .FirstOrDefaultAsync();
            int CurrentNO;
            if (cs!=null) 
            {
                CurrentNO =Convert.ToInt32(cs.CommentNo) ;
                CurrentNO++;
            }
            else 
            {
                CurrentNO = 1;
            }
            data.CommentNo = CurrentNO;
            data.ReplyDate = DateTime.Now.ToString();
            data.UserIp = HttpContext.Connection.RemoteIpAddress.ToString();
            data.IsShow = "true";
            data.Username = User.Identity.Name;
            _db.Add(data);

            var ks= await _db.Kratoos.Where(k=>k.Kid==data.Kid).FirstOrDefaultAsync();
            var replycount = ks.ReplyCount;
            replycount++;
            ks.ReplyCount = replycount;
            _db.Update(ks);

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(kratooComments), new { id = data.Kid });

        }
        [Authorize(Roles = "Admin,Staff")]
        public async Task<IActionResult> Delete()
        {
            var ks = _db.Kratoos.OrderByDescending(k => k.RecordDate).Where(u => u.IsShow == "true");
            if (ks == null)
            {
                return NotFound();
            }
            return View(await ks.ToListAsync());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Staff")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
          
            var kratoo = await _db.Kratoos.FindAsync(id);
            if (kratoo == null)
            {
                return NotFound();
            }
            var comments = _db.Comments.Where(c => c.Kid == id);
            _db.Comments.RemoveRange(comments);

            // ลบ Kratoo
            _db.Kratoos.Remove(kratoo);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin,Staff")]
        public async Task<IActionResult>DeletekratooComments(int id)
        {
            var kc = await _db.Kratoos
                .Where(i => i.IsShow == "true")
                .FirstOrDefaultAsync(k => k.Kid == id);

            if (kc == null)
            {
                return NotFound();
            }
            if (id != kc.Kid)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var viewcount = kc.ViewCount;
                    viewcount++;
                    kc.ViewCount = viewcount;
                    _db.Update(kc);
                    await _db.SaveChangesAsync();
                }
                catch (DBConcurrencyException)
                {
                    var result = _db.Kratoos.Any(k => k.Kid == id);
                    if (result == false)
                    {
                        return NotFound();
                    }
                }
            }
            IQueryable<Comment> cs = _db.Comments
                .OrderBy(c => c.CommentNo)
                .Where(i => i.IsShow == "true")
                .Where(j => j.Kid == id);

            var viewmodel = new KratooCommentViewModel()
            {
                Kratoo = kc,
                CommentList = cs
            };
            ViewData["KratooCommentViewModel"] = viewmodel;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteComment(int commentId, int kid)
        {
            var comment = await _db.Comments
                .FirstOrDefaultAsync(c => c.CommentNo == commentId && c.Kid == kid);
            if (comment == null || comment.Username != User.Identity.Name)
            {
                return NotFound();
            }

            _db.Comments.Remove(comment);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(kratooComments), new { id = kid });
        }


        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var kratoo = await _db.Kratoos.FindAsync(id);
            if (kratoo == null || kratoo.Username != User.Identity.Name)
            {
                return NotFound();
            }

            ViewData["CategoriesLists"] = new SelectList(_db.Categories, "CategoryId", "CategoryName", kratoo.CategoryId);
            return View(kratoo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Kratoo data)
        {
            if (id != data.Kid || data.Username != User.Identity.Name)
            {
                return NotFound();
            }
            var existingKratoo = await _db.Kratoos.FindAsync(id);
            if (existingKratoo == null)
            {
                return NotFound();
            }
            existingKratoo.KratooTopic = data.KratooTopic;
            existingKratoo.KratooDetails = data.KratooDetails;
            existingKratoo.CategoryId = data.CategoryId;
        
            try
            {
                _db.Update(existingKratoo);
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_db.Kratoos.Any(k => k.Kid == id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(Index));
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-select/css/select.bootstrap4.min.css">

    <!-- sweet alert2 -->
    <link rel="stylesheet" href="~/adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css">

    <!-- select2-->
    <link rel="stylesheet" href="~/adminlte/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- daterangepicker-->
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- datepicker-->
    <link rel="stylesheet" href="~/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

    <link rel="stylesheet" href="~/css/w3.css" />

    <link rel="stylesheet" href="~/css/site.css?v=1.2" asp-append-version="true" />
   
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">


        <partial name="_NavbarPartial" />
        <partial name="_SidebarPartial" />

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div class="mx-4">
                @RenderBody()
            </div>
        </div>
        <!-- /.content-wrapper -->


        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <script src="~/adminlte/plugins/inputmask/jquery.inputmask.min.js"></script>
    <script src="~/adminlte/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/jquery-serialzejson/jquery.serializejson.min.js"></script>

    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/jszip/jszip.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script src="~/adminlte/plugins/datatables-select/js/dataTables.select.min.js"></script>
    <script src="~/adminlte/plugins/datatables-select/js/select.bootstrap4.min.js"></script>

    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>

    <!-- Sweet Alert 2 -->
    <script src="~/adminlte/plugins/sweetalert2/sweetalert2.all.min.js"></script>


    <!--Select 2 -->
    <script src="~/adminlte/plugins/select2/js/select2.full.min.js"></script>


    <!--Date fns -->
    <script src="~/lib/date-fns/date_fns.min.js"></script>

    <!-- moment -->
    <script src="~/adminlte/plugins/moment/moment.min.js"></script>

    <!-- daterangepicker -->
    <script src="~/adminlte/plugins/daterangepicker/daterangepicker.js"></script>

    <!-- datepicker -->
    <script src="~/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- validation -->
    <script src="~/adminlte/plugins/jquery-validation/jquery.validate.min.js"></script>


    @*<script src="~/adminlte/plugins/chart.js/Chart.js"></script>*@

    <script src="~/js/site.js?v=1.2" asp-append-version="true"></script>
    @*<script src="~/js/budgetadjust.js" asp-append-version="true"></script>*@

    <!--AspNetCoreHero.ToastNotification -->
  @*   @await Component.InvokeAsync("Notyf") *@

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_NavbarPartial.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Search Bar in the center -->
    <div class="d-flex justify-content-center w-100">
        <div class="input-group col-4">
            <form asp-controller="Webboard" asp-action="Search" class="w-100">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="search-icon" autocomplete="off" />
                    <span class="input-group-text" id="search-icon" role="button" tabindex="0" onclick="this.parentElement.querySelector('form').submit()">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
            </form>

        </div>
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <!-- Right navbar links -->
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <form asp-controller="Account" asp-action="Logout" method="post">
                    <button type="submit" class="btn btn-primary">
                        Logout
                    </button>
                </form>
            </li>
        </ul>
    }
</nav>
<!-- /.navbar -->

Views/Shared/_SidebarPartial.cshtml
@* @using Microsoft.AspNetCore.Identity; *@
@* @inject UserManager<User> userManager *@

@{
    //var user = "";
    // var user = await userManager.GetUserAsync(User);
    //  var roles = await userManager.GetRolesAsync(user);
    //int userid = Int32.Parse(@User.FindFirst("PERIDX")?.Value);
}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a asp-controller="Home" asp-action="Index" class="brand-link d-flex align-items-center" style="text-decoration: none">
        @*  <div class="brand mr-2">
        <img src="~/image/jaspallogo.jpg" alt="Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        </div>
        *@
        <span class="brand-text font-weight-light">DevWebboard</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/adminlte/dist/img/UserAvatar.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a class="nav-link" asp-controller="Member" asp-action="Index" role="button">
                    @User.Identity.Name
                </a>
            </div>
        </div>


        <!-- Sidebar Menu -->
        <nav class="mt-2">

            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">



                <li class="nav-item">
                    <a class="nav-link text-uppercase"
                       aria-current="page" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> <p>Home</p> </a>
                </li>
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link text-uppercase " asp-area="" asp-controller="Account" asp-action="Index">  <i class="fas fa-plus"></i><p>Register</p> </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase " asp-area="" asp-controller="Account" asp-action="Login"><i class="fas fa-sign-in-alt"></i><p>Login</p> </a>
                    </li>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("Member") || User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-uppercase" asp-area="" asp-controller="Webboard" asp-action="Index"><i class="fas fa-comment-alt"></i>  <p>Webboard</p> </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-uppercase" asp-area="" asp-controller="Webboard" asp-action="Create"><i class="fas fa-plus"></i>  <p>New Post</p> </a>
                        </li>
                    }
                }
                @if (User.Identity.IsAuthenticated)
                {
                  @*   <li class="nav-item">
                        <a class="nav-link text-uppercase" asp-controller="Member" asp-action="Index"><i class="fas fa-user"></i>  <p>Profile</p> </a>
                    </li> *@

                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-uppercase" asp-controller="Admin" asp-action="Dashboard"><i class="fas fa-users-cog"></i>  <p> Admin Menu</p></a>
                        </li>
                    }



                }

            </ul>

        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

Views/Shared/_kratooSearch.cshtml
<div class="row jusify-content-center align-items-center">
    <div class="col-lg-12">
        <form asp-controller="Webboard" asp-action="Search">
            <div class="input-group">
                <input type="text" name="q" class="form-control mr-1" placeholder="ค้นหาเลยจ้าาาาาา" />
                <button type="submit" class="btn btn-success">ค้นหา</button>
            </div>
        </form>
    </div>
</div>